# -*- coding: utf-8 -*-
"""2023078083 조예지 0319.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1onwgARHZf6JjZz3jRK6SQfsshh-UzusV
"""

from typing import List,Tuple,Dict

st_info: List[Tuple[str,str,int,int,int,int,float, str, int]]=[]
#그냥 튜플로 저장하면 마지막값만 저장되기 때문에 리스트로 사용

def get_info():
  id, name, eng, c, python = input("학번, 이름, 영어, C-언어, 파이썬 점수를 입력하세요 (공백으로 구분): ").split();
  eng, c, python = int(eng), int(c), int(python)

  total = get_total(eng,c,python)
  avg = get_avg(total)
  grade = get_grade(avg)

  st_info.append((id, name, eng, c, python, total, avg, grade,0))

def get_total(eng,c,python) :

  return eng + c + python

def get_avg(total) :
  return round(total/3,2)

def get_grade(avg) :
  if avg >= 90 :
    return 'A'
  elif avg >= 80 :
    return 'B'
  elif avg >= 70 :
    return 'C'
  elif avg >= 60 :
    return 'D'
  else:
     return'F'

def calculate_ranks():
    global st_info
    st_info.sort(key=lambda x: x[5], reverse=True)
    for rank, student in enumerate(st_info, start=1):
        st_info[rank - 1] = student[:8] + (rank,)

def print_scores():
    print("\n성적 관리 프로그램")
    print("=" * 80)
    print("학번\t\t이름\t영어\tC-언어\t파이썬\t총점\t평균\t학점\t등수")
    print("=" * 80)
    for student in st_info:
        print(f"{student[0]}\t{student[1]}\t{student[2]}\t{student[3]}\t{student[4]}\t"
              f"{student[5]}\t{student[6]}\t{student[7]}\t{student[8]}")


for i in range(5):
  get_info()

calculate_ranks()

print_scores()